/**
 * /sitemap.xml: the old GoDaddy site advertised this URL, so keep it working after the switch.
 * It is a sitemap index pointing at the real sitemap generated by @astrojs/sitemap
 * (sitemap-0.xml directly, because a sitemap index cannot nest another index).
 * The GitHub Pages demo has no sitemap, so it returns an empty index there.
 */
import type { APIRoute } from 'astro';
import { isDemo } from '../lib/env';
import { site } from '../data/site';

export const GET: APIRoute = () => {
  const entry = isDemo ? '' : `<sitemap><loc>${site.url}/sitemap-0.xml</loc></sitemap>`;
  const body = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${entry}</sitemapindex>\n`;
  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
