/**
 * /sitemap.xml: the old GoDaddy site advertised this URL, so keep it working after the switch.
 * It is a sitemap index pointing at the real sitemap generated by @astrojs/sitemap.
 * (It points at sitemap-0.xml directly, because a sitemap index cannot nest another index.)
 */
import type { APIRoute } from 'astro';

export const GET: APIRoute = ({ site }) => {
  const loc = new URL('sitemap-0.xml', site).href;
  const body =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    `<sitemap><loc>${loc}</loc></sitemap>` +
    '</sitemapindex>\n';
  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
